# Apunts Variàbles:


In [2]:
a = 3
print(type(a))


<class 'int'>


In [3]:
1j

1j

In [4]:
1j * 0

0j

In [1]:
abs(9 + 5j)

10.295630140987

In [2]:
complejo = 9 + 5j
complejo.real

9.0

In [3]:
complejo.imag

5.0

### Llistes:

In [26]:
llista = [1, 3.66, "HOla", 19, -0804.9887, None, True, False, 'ultim', ] #Pot acabar amb coma
print(llista)

[1, 3.66, 'HOla', 19, -804.9887, None, True, False, 'ultim']


In [27]:
llista[-1] #Ens quedem amb l'últim element

'ultim'

In [28]:
llista[0] #Com en C comença amb 0

1

In [29]:
llista[-2] #Ens dona el penúltim, i així successivament

False

In [30]:
llista[-20] #Donara error

IndexError: list index out of range

In [31]:
llista

[1, 3.66, 'HOla', 19, -804.9887, None, True, False, 'ultim']

In [32]:
llista[0:-1:2] #Del 0 al últim, cada 2 sense mostrar-nos l'últim, ja que mostra fins al postúltim

[1, 'HOla', -804.9887, True]

In [33]:
#Per mostrar fins al final i els parells el deixem buit:
llista[0::2]

[1, 'HOla', -804.9887, True, 'ultim']

In [23]:
llista[3:] #Ens mostrarà desde el 3 cap endavant

[19, -804.9887, None, True, False]

In [25]:
llista[-3:] #Ens donara desde el antepenúltim fins al final

[None, True, False]

In [34]:
llista[::-1] #Ens mostra la llista al revés

['ultim', False, True, None, -804.9887, 19, 'HOla', 3.66, 1]

In [35]:
llista[3::-1] #del llista[3] fins al principi

[19, 'HOla', 3.66, 1]

In [36]:
llista.append("nou element")
llista

[1, 3.66, 'HOla', 19, -804.9887, None, True, False, 'ultim', 'nou element']

In [40]:
# Per afegir vàris elements:
llista.append([99, 88, "append_llista"])
print(llista)

[1, 3.66, 'HOla', 19, -804.9887, None, True, False, 'ultim', 'nou element', [99, 88, 'append_llista'], [99, 88, 'append_llista']]


In [44]:
#Per afegir una llista a una altre (sense ser una llista dins d'una altra):
llista.extend([3.4, 9])
llista

[1,
 3.66,
 'HOla',
 19,
 -804.9887,
 None,
 True,
 False,
 'ultim',
 'nou element',
 [99, 88, 'append_llista'],
 [99, 88, 'append_llista'],
 3.4,
 9]

In [45]:
# Per treure un element del final o per treure un element amb un índex:
llista.pop()


9

In [47]:
llista.pop(10)

[99, 88, 'append_llista']

In [48]:
llista.remove(19) # Borrarà la primera aparició de 19
print(llista)
#Si ho tornem a fer peta pq ja no hi ha

[1, 3.66, 'HOla', -804.9887, None, True, False, 'ultim', 'nou element', [99, 88, 'append_llista']]


In [49]:
# Per contar quants elements iguals hi ha
llista.append(1)
llista.count(1)


3

In [53]:
llista.__len__() # Per saber la longitud

11

In [54]:
#per modificar un element
llista[5] = 42
llista

[1,
 3.66,
 'HOla',
 -804.9887,
 None,
 42,
 False,
 'ultim',
 'nou element',
 [99, 88, 'append_llista'],
 1]

In [60]:
#per insertar un objecte a un lloc de la llista
llista.insert(4, "insertaaat") 
llista

[1,
 3.66,
 'HOla',
 -804.9887,
 'insertaaat',
 None,
 42,
 False,
 'ultim',
 'nou element',
 [99, 88, 'append_llista'],
 1]

## Tuples:
-----
Son iguals que les llistes però són inmutables. Si dintre hi ha objectes mutables (com una llista) es poden mutar

Són objectes separats per comes

Serveixen per raons d'eficiència, ja que és més eficient que una llista. 
A part, amb els objectes inmutables podem construïr objectes "Hashables"

In [ ]:
tupla = (9, "hola", 24, 42, "aAaAaAa", [2, 5])
tupla

(9, 'hola', 24, 42, 'aAaAaAa', [2, 5])

In [57]:
#Un cop creada ja no es pot modificar
tupla[3] = 6

TypeError: 'tuple' object does not support item assignment

In [59]:
# Si que podem modificar la llista de dintre
tupla[-1][0] = 8
tupla

(9, 'hola', 24, 42, 'aAaAaAa', [8, 5])

## Claus HASH

No poden ser modificables de cap manera, ha de ser un objecte completament INMUTABE


In [61]:
hash("hola")


5745914321976161911

In [63]:
hash(("hola", 4, 5.9, 42)) # Li posem una llista dintre

95736830209777785

In [64]:
hash([2, 5]) # No funciona ja que al tenir una llista dintre aquesta seria modificable i els objectes hash no poden ser-ho

TypeError: unhashable type: 'list'

## Conjunts (Set)

Un conjunt és una col·lecció d'objectes no repetits, no indexables i HASABLES.

No podem posar en un conjunt un objecte que no sigui hashable. Una tupla no es podría.

No pot tenir idèntics

**Conjunts d'Euler:** Objectes separats per ',' i tancats per claus '{}'

**Utilitat:** Quedarnos amb els elements no repetits d'una llista


In [66]:
conjunt = {1, 4, 7, 42, 44, 4, 1} #Elimina els duplicats
print(conjunt)

{1, 4, 7, 42, 44}


In [68]:
conjunt = {"Hola", 4, 2, "Adeu", 3, 0, 1, 2, "Hola", 3}
print(conjunt)

{0, 'Adeu', 2, 3, 4, 1, 'Hola'}


In [69]:
conjunt.pop() #Elimina el primer element

0

In [71]:
conjunt

{1, 2, 3, 4, 'Adeu', 'Hola'}

In [72]:
conjunt.add(5)

In [73]:
print(conjunt)

{'Adeu', 2, 3, 4, 1, 'Hola', 5}


In [75]:
conjunt2 = {'hola', "adeu", "HOLA", "ADEU"}
conjunt2

{'ADEU', 'HOLA', 'adeu', 'hola'}

In [77]:
# Intersecció
print(conjunt & conjunt2)

set()


In [78]:
# Unió
print(conjunt | conjunt2)

{'Adeu', 2, 3, 4, 1, 5, 'adeu', 'HOLA', 'Hola', 'hola', 'ADEU'}


In [79]:
# Diferencia
conjunt - conjunt2

{1, 2, 3, 4, 5, 'Adeu', 'Hola'}

In [80]:
#Operador comparació
conjunt > {1, 2, 3, 4, 5, "HOLA"}

False

In [81]:
conjunt

{1, 2, 3, 4, 5, 'Adeu', 'Hola'}

In [83]:
conjunt == {1, 2, 3, 4, 5, 'Adeu', 'Hola'}

True

In [86]:
conjunt.add("altre")
conjunt

{1, 2, 3, 4, 5, 'Adeu', 'Hola', 'altre'}

##### Es pot crear un conjunt de conjunts? 
NOOOOOO

In [90]:
conjunt3 = {4, 2, conjunt} # Els conjunts no són Hashables

TypeError: unhashable type: 'set'

In [2]:
conjunto = {1, "ss", 9.5}
conjunto2 = {77, "hola", 8.87}
print(conjunto)
conjunto = conjunto.union(conjunto2)
print(conjunto)

{1, 'ss', 9.5}
{1, 'hola', 8.87, 'ss', 77, 9.5}


In [4]:
# Ahora podemos meter el conjunto frozenset dentro de otro conjunto
frozen = frozenset(conjunto)
conjunto3 = {67, 'holii', frozen}
print(conjunto3)

{67, 'holii', frozenset({1, 'hola', 8.87, 'ss', 77, 9.5})}


In [5]:
#asignación múltiple:
a, b, c = 45, 9, "adeu"
print(a)
print(b)
print(c)

45
9
adeu


In [7]:
# Per no fer temporals:
a, b, c = b, c, a
print(a)
print(b)
print(c)

9
adeu
45


## Diccionaris

Un objecte que conté items que tenen assignada una clau

In [14]:
diccionari = {1 : "un",
              2 : "dos",
              3 : "tres",
              4 : "quatre",
              80 : "vuitanta",
             }
diccionari

{1: 'un', 2: 'dos', 3: 'tres', 4: 'quatre', 80: 'vuitanta'}

In [16]:
diccionari[3]

'tres'

In [18]:
1 in diccionari #Només és amb la clau

True

In [19]:
"un" in diccionari

False

In [23]:
# Es pot afegir talcual
diccionari[0] = None
print(diccionari)
# Es pot modificar també
diccionari[0] = 'ZERO'
print(diccionari)

{1: 'un', 2: 'dos', 3: 'tres', 4: 'quatre', 80: 'vuitanta', 0: None}
{1: 'un', 2: 'dos', 3: 'tres', 4: 'quatre', 80: 'vuitanta', 0: 'ZERO'}


#### Mètodes:


In [24]:
diccionari.values()

dict_values(['un', 'dos', 'tres', 'quatre', 'vuitanta', 'ZERO'])

In [25]:
diccionari.items()

dict_items([(1, 'un'), (2, 'dos'), (3, 'tres'), (4, 'quatre'), (80, 'vuitanta'), (0, 'ZERO')])

In [27]:
4 in diccionari.items()

False

In [29]:
(4, 'quatre') in diccionari.items()

True

In [26]:
diccionari.keys()

dict_keys([1, 2, 3, 4, 80, 0])

In [30]:
diccionari[None] = 'res'
diccionari

{1: 'un',
 2: 'dos',
 3: 'tres',
 4: 'quatre',
 80: 'vuitanta',
 0: 'ZERO',
 None: 'res'}

### Elements Buits:


In [32]:
llista = list()
# o
llista = []

[]

In [36]:
tuppla = tuple()
# o 
tuppla2 = ()
tuppla

()

In [40]:
conjunt = set()
# o 
conjunt2 = {} #Aixi creem un diccionari
conjunt
# Per crear un conjunt buit només es pot fer amb el constructor

set()

In [41]:
diccionari = dict()
# o
diccionari = {}
diccionari

{}

In [44]:
conjunt = set()
conjunt.add(35)
conjunt.add(42)
conjunt.add((1, None, 9.8))
conjunt

{(1, None, 9.8), 35, 42}

In [46]:
conjunt.add([5, 8]) # NO podem afegir una llista al conjunt

TypeError: unhashable type: 'list'

## Cadenas de Texto

In [48]:
# Podem utilitzar cadenes simples o dobles
'Amb cometes simples'
"Amb cometes dobles"

'Amb cometes dobles'

In [49]:
# Amb cometes simples hi pot haber un problema
'Ell juga a futbol amb l'Oriol'
# Utilitzem les dobles en aquest cas

SyntaxError: unterminated string literal (detected at line 2) (1086739349.py, line 2)

In [51]:
# Una opció és utilitzar la barra invertida
'\''

"'"

In [54]:
# En aquest exemple eliminem la '\n'
'Hola que tal \
com estas, be? \
Jo si'

'Hola que tal com estas, be? Jo si'

In [62]:
# El que fa el '\r' es colocar el cursor a primera linea i continuar escribint
print('Hola que tal\r adios') 

 adiosue tal


In [65]:
cadena_llarga = ''' És una cadena llarga que te moltes linees
que pot servir per documentar fitxers
o pel que vulguis '''

print(cadena_llarga)

 És una cadena llarga que te moltes linees
que pot servir per documentar fitxers
o pel que vulguis 


In [66]:
# Multiplicació de cadenes
"pdbq" * 8

'pdbqpdbqpdbqpdbqpdbqpdbqpdbqpdbq'

In [69]:
"=" * 75

'==========================================================================='

In [76]:
"Hola" + " " + "Adios " + str(conjunt)

'Hola Adios {42, 35, (1, None, 9.8)}'

In [77]:
print("Hola" + " " + "Adios " + str(conjunt))

Hola Adios {42, 35, (1, None, 9.8)}


In [81]:
print("Mi numero: " + str(345) + "; mi altura" + str(9+9j))

Mi numero: 345 mi altura(9+9j)


In [84]:
f"""esto es una cadena f, {'*' * 9} podemos escribir entre llaves lo que queramos {conjunt}"""

'esto es una cadena f, ********* podemos escribir entre llaves lo que queramos {42, 35, (1, None, 9.8)}'

In [87]:
f'Hola {cadena_llarga[::-1]}: escribim la cadena al revés'

'Hola  siugluv euq lep o\nsrextif ratnemucod rep rivres top euq\nseenil setlom et euq agrall anedac anu sÉ : escribim la cadena al revés'

In [93]:
# Les cadenes són inmutables
cadena_llarga[3:8:] = "olpa"

TypeError: 'str' object does not support item assignment

In [100]:
# Cadena bites
b"hola que tal 67"
b"Hola, què tal" #No funciona pq el accent no és un caràcter ASCII

b'hola que tal 67'

In [97]:
b"hola que tal 67".upper()

b'HOLA QUE TAL 67'

In [98]:
b"hola que tal 67".title()

b'Hola Que Tal 67'

In [103]:
lista = [1, 3.9, "hola"]
del lista[1]
print(lista)

[1, 'hola']


In [105]:
# Desvinculem l'objecte de la variable
del lista
lista

NameError: name 'lista' is not defined

## Clase de Tipo Iterable




### Iterador

In [6]:
colors = {"blau", "groc", "verd"}
iterator = iter(colors)

print(next(iterator))
print(next(iterator))
print(next(iterator))

groc
verd
blau


In [16]:
rang = range(10)
iterador = iter(rang)
print(next(iterador))
print(next(iterador))
print(next(iterador))
print(next(iterador))
next(iterador)
next(iterador)
next(iterador)
next(iterador)

0
1
2
3


7

In [19]:
rango = range(327 ** 42, 330 ** 200)
rango[-1]
# Els numeros no estan en memòria, es generen al demanarlos

504414979892390296667771300610953433582177415142724640385043847481569913987226620136227616819038944925700130237863681241961907820372286600667741210983984032726665779257776482073026378631304152581884581260981320184308551345436157178230447214544777225449382086628103952806065731252042425405800483191593600099999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999

In [20]:
rango = range(33, 71, 4) #Del 33 al 71 amb increments de 4 en 4
list(rango)

[33, 37, 41, 45, 49, 53, 57, 61, 65, 69]

#### NoneType

In [21]:
type(None)

NoneType

#### Elipsis

In [25]:
... #Per exemple per fer un ndarray i no sabem encara quantes dimensions té

Ellipsis

In [23]:
Ellipsis # Evalua a true
type(Ellipsis)

ellipsis

#### Exceptions

In [27]:
excep # Ens genera la excepció 'NameError'

NameError: name 'excep' is not defined

In [31]:
import numpy as np

tensor = np.array([[[1, 2], [3, 4]],[[5, 6], [7, 8]]])
tensor

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [33]:
tensor[:,:,0] #Els valors 0 de les diferents dimensions

array([[1, 3],
       [5, 7]])

In [35]:
tensor[..., 0] #Ens donara el mateix que abans pero ara ho farà també per més dimensions

array([[1, 3],
       [5, 7]])

## Estructures de condicions


#### If / else

In [39]:
a = 8;

if a > 10:
    print("Hola")
elif a <= 10 and a >= 5:
    print("Adeu")
else:
    print("Cap")


Adeu


In [49]:
num = 33
if not num % 2:
    print("Par!")
else:
    print("Impar!")

Impar!


#### Operador Ternario

expressionTrue if condición else expresionFalse

In [52]:
# Operador per fer el valor absolur
num = -13

num if num > 0 else -num

13

### Estructuras Iterativas

##### For i While

In [55]:
numero = 6
while numero > 0:
    print(numero)
    numero -= 1


6
5
4
3
2
1


In [57]:
colores = {"red", "green", "blue", "black"}

while colores:
    print (f"{colores.pop()}")

green
black
red
blue


##### Asignación evaluada (morsa

**:=**

In [62]:
colors = {"red", "green", "blue", "black"}
(color := colors.pop())

'green'

In [64]:
while (color := colors.pop()):
    print(color)
    print(color * 2)

black
blackblack
red
redred
blue
blueblue


KeyError: 'pop from an empty set'

#### For

In [67]:
colors = {"red", "green", "blue", "black"}

for color in colors:
    print(f"{color}")

green
black
red
blue


In [71]:
colors = {"red", "green", "blue", "black"}

for color in colors:
    print(color)
    if color == "blue": continue
    elif color == "red": break
else:#només s'executa si el bucle acaba de forma inesperada com amb un break
    print("Ya no quedan colores")

green
black
red


In [78]:
import numpy as np

vector = np.random.randint(0, 10, 5) #5 enters entre 0 i 10
print (vector)
for i in range(len(vector)):
    print(vector[i])

[9 7 1 0 7]
9
7
1
0
7
